site_name: IC的帆哥
nav:
  - Home:  index.md
  - About: about.md
  - Reading: 
      - 管理大师 : Reading/Drucker.md
      - 人生过半的启示 : Reading/zhanghui.md
      - 稻盛和夫: Reading/Daosheng.md
  - Thinking:
      - 父亲节19: Thinking/father19.md
      - 父亲节22: Thinking/father22.md
      - 奇遇: Thinking/neiguan.md
      - 配吗？: Thinking/peima.md
  - Note:
      - DDR struct: Note/DDR.md
      - Simpoint: Note/simpoint.md
theme:
  name: readthedocs

